let titulo = $(document.createElement('h2'))
                .attr ('class', 'Títulos')
                .attr ('id', "Nosotros")
                .html ('Nosotros')
                .appendTo ('#Nos')
let carrosuel = $(document.createElement('div'))
                .attr ('class', 'CarrouselNos')
                .attr ('id', "CarrouselNos")        
                .appendTo ('#Nos')
let textoN = $(document.createElement('div'))
               .attr('class', 'texto')
               .attr('id','textoN')
               .html(`
               Nosotros somos una hamburguesería que nació en el año <strong>2015</strong> en el barrio de Villa Crespo. Somos fanáticos del picante y de la cerveza, por eso los invitamos a venir a comer nuestra hamburguesa más picante la "DEATH WISH". <strong>Si lográs terminartela toda en menos de 10 minutos la cuenta va de nuestra parte!</strong>
               `)
               .appendTo('#Nos');
               console.log (titulo)
let carrosuelN = $(document.createElement('div'))
                .attr ('class', 'carrouselNos containerNos')      
                .appendTo ('#Nos')
let carrosuelAnterior = $(document.createElement('div'))
                .attr ('class', 'botones anteriorNos')      
                .html('<')
                .appendTo ('#Nos')
let carrosuelSiguiente = $(document.createElement('div'))
                .attr ('class', 'botones siguienteNos')      
                .html('>')
                .appendTo ('#Nos')
let carrosuelImg = $(document.createElement('img'))
                .attr ('class', 'ImagenCarrouselNos')      
                .attr ('src', 'fotos/carrousel/Imagen.jpg ')    
                .appendTo ('#Nos')